# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23cd63da59955cd910683085737d93e73be039130c31a2b7afaa1b381b32db9352fbe51377868d4e4a2bea934cdc94175e408398693b274b081751d311a57077

test:
  secret_key_base: 676f032bf743977eff64657b83683305664edad3bb14957043e3ff2970fd739f5774289ddd8b6d28ed00f53fdfcf66fe00b4e6b7468eea5be5d08cd8ea49b356

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
